# This workflow publishes to PyPi using Twine when a new release is created.

# name: Publish to PyPI

# on: 
#     push:
#         branches:
#           - master

# jobs:
#     publish:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v4

#         - name: Set up Python
#           uses: actions/setup-python@v5
#           with:
#             python-version: '3.8.13'

#         - name: Install dependencies
#           run: |
#             python -m pip install --upgrade pip
#             pip install -r requirements.txt
#             pip install build

#         - name: Build package
#           run: python -m build

#         - name: Publish package to PyPI
#           environment:
#             name: pypi
#             url: https://pypi.org/project/dimo-python-sdk/
#           permissions:
#             id-token: write
#           steps:
#             - name: Publish package distributions to PyPI
#               uses: pypa/gh-action-pypi-publish@release/v1